//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 04:51:01 PM EDT 
//

package com.alphasystem.sarfengine.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * <p>
 * Java class for ConjugationTemplate complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <pre>
 * &lt;complexType name="ConjugationTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alphasystem.com/sarfengine/xml/model}data" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConjugationTemplate", propOrder = {"chartConfiguration",
        "data"})
public class ConjugationTemplate {

    protected List<ConjugationData> data;

    @XmlElement(name = "chart-configuration")
    protected ChartConfiguration chartConfiguration;

    public ConjugationTemplate() {
        setChartConfiguration(null);
    }

    public ChartConfiguration getChartConfiguration() {
        return chartConfiguration;
    }

    public void setChartConfiguration(ChartConfiguration chartConfiguration) {
        this.chartConfiguration = chartConfiguration == null ? new ChartConfiguration()
                : chartConfiguration;
    }

    /**
     * Gets the value of the data property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the data property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <p>
     * <pre>
     * getData().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConjugationData }
     */
    public List<ConjugationData> getData() {
        if (data == null) {
            data = new ArrayList<>();
        }
        return this.data;
    }

    /**
     * Sets the value of the data property.
     *
     * @param data allowed object is {@link ConjugationData }
     */
    public void setData(List<ConjugationData> data) {
        this.data = data;
    }

    public ConjugationTemplate withData(Collection<ConjugationData> values) {
        if (values != null) {
            getData().addAll(values);
        }
        return this;
    }

    public ConjugationTemplate withData(ConjugationData... values) {
        if (values != null) {
            for (ConjugationData value : values) {
                getData().add(value);
            }
        }
        return this;
    }

    public ConjugationTemplate withData(List<ConjugationData> data) {
        setData(data);
        return this;
    }

}
