//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 04:51:01 PM EDT 
//

package com.alphasystem.sarfengine.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.alphasystem.sarfengine.xml.model
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Chart_QNAME = new QName(
            "http://www.alphasystem.com/sarfengine/xml/model", "chart");
    private final static QName _Data_QNAME = new QName(
            "http://www.alphasystem.com/sarfengine/xml/model", "data");
    private final static QName _RootWord_QNAME = new QName(
            "http://www.alphasystem.com/sarfengine/xml/model", "root-word");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.alphasystem.sarfengine.xml.model
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ConjugationTemplate } {@code >}
     */
    @XmlElementDecl(namespace = "http://www.alphasystem.com/sarfengine/xml/model", name = "chart")
    public JAXBElement<ConjugationTemplate> createChart(
            ConjugationTemplate value) {
        return new JAXBElement<ConjugationTemplate>(_Chart_QNAME,
                ConjugationTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link ConjugationData }
     */
    public ConjugationData createChartData() {
        return new ConjugationData();
    }

    /**
     * Create an instance of {@link ConjugationTemplate }
     */
    public ConjugationTemplate createChartTemplate() {
        return new ConjugationTemplate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConjugationData }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://www.alphasystem.com/sarfengine/xml/model", name = "conjugation")
    public JAXBElement<ConjugationData> createConjugation(ConjugationData value) {
        return new JAXBElement<ConjugationData>(_Data_QNAME,
                ConjugationData.class, null, value);
    }

    /**
     * Create an instance of {@link RootWord }
     */
    public RootWord createRootWord() {
        return new RootWord();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootWord }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://www.alphasystem.com/sarfengine/xml/model", name = "root-word")
    public JAXBElement<RootWord> createRootWord(RootWord value) {
        return new JAXBElement<RootWord>(_RootWord_QNAME, RootWord.class, null,
                value);
    }

    /**
     * Create an instance of {@link RootLetters }
     *
     * @return
     */
    public RootLetters getRootLetters() {
        return new RootLetters();
    }

}
